server:
  port: 10086
spring:
  application:
    name:
eureka:
  client:
    fetch-registry: false  # 是否注册自己的信息到EurekaServer，默认是true
    register-with-eureka: false # 是否拉取其他服务的信息，默认true
    service-url: # EurekaServer的地址
      defaultZone: http://127.0.0.1:${server.port}/eureka
  server:
    enable-self-preservation: false # 关闭自我保护
    eviction-interval-timer-in-ms: 5000 # 每隔5秒进行一次服务列表清理 失效剔除