server:
  port: 8086
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: '0779'
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
  rabbitmq:
    username: leyou
    password: leyou
    virtual-host: /leyou
    host: 192.168.86.129
  redis:
    host: 192.168.86.129
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
mybatis:
  type-aliases-package: com.leyou.user.pojo
