server:
  port: 8085
spring:
  application:
    name: ly-sendMassage
  rabbitmq:
    username: leyou
    password: leyou
    host: 192.168.86.129
    virtual-host: /leyou
  redis:
    host: 192.168.86.129
ly:
  massage:
    accessKeyId: LTAI4GAxKqVAYYXkwx61XVbg
    accessKeySecret: MftIZHAathmULlHfmd2ubjEtMYZvbV
    signName: 乐优商城 #签名名称
    verifyCodeTemplate: SMS_193514641 #模板名称